# -*- coding: utf-8 -*-
"""IACVfine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmAzPJ1qeiOv52BJm4NyqBXywQeKnSnn

**Install mediapipe**
"""

!pip -q install ultralytics opencv-python filterpy supervision mediapipe

"""**Download MediaPipe PoseLandmarker model**"""

import os
import urllib.request

MODEL_URL = "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task"
MODEL_PATH = "pose_landmarker_lite.task"

if not os.path.exists(MODEL_PATH):
    print("Downloading MediaPipe PoseLandmarker model...")
    urllib.request.urlretrieve(MODEL_URL, MODEL_PATH)
    print("Saved:", MODEL_PATH)
else:
    print("Model already present:", MODEL_PATH)

"""**data structures + helper**"""

import cv2
import numpy as np
from dataclasses import dataclass

@dataclass
class Detection:
    xyxy: np.ndarray   # (4,) float32
    conf: float
    cls: int
    track_id: int | None = None

def clamp_box(xyxy, w, h):
    x1, y1, x2, y2 = xyxy
    x1 = max(0, min(int(x1), w - 1))
    y1 = max(0, min(int(y1), h - 1))
    x2 = max(0, min(int(x2), w - 1))
    y2 = max(0, min(int(y2), h - 1))
    if x2 <= x1: x2 = min(w - 1, x1 + 1)
    if y2 <= y1: y2 = min(h - 1, y1 + 1)
    return np.array([x1, y1, x2, y2], dtype=np.int32)

def xyxy_center(xyxy: np.ndarray) -> np.ndarray:
    x1, y1, x2, y2 = xyxy
    return np.array([(x1 + x2) / 2.0, (y1 + y2) / 2.0], dtype=np.float32)

def adaptive_crop(frame_bgr, xyxy, scale=1.8):
    h, w = frame_bgr.shape[:2]
    x1, y1, x2, y2 = xyxy
    cx, cy = (x1 + x2) / 2, (y1 + y2) / 2
    bw, bh = (x2 - x1), (y2 - y1)

    bw2, bh2 = bw * scale / 2, bh * scale / 2
    crop_xyxy = np.array([cx - bw2, cy - bh2, cx + bw2, cy + bh2], dtype=np.float32)
    crop_xyxy = clamp_box(crop_xyxy, w, h)

    x1, y1, x2, y2 = crop_xyxy
    roi = frame_bgr[y1:y2, x1:x2].copy()
    return roi, crop_xyxy

def measurement_from(det: Detection, pose_com: np.ndarray | None) -> np.ndarray:
    return pose_com if pose_com is not None else xyxy_center(det.xyxy)

"""**YOLOv8 detector (person)**"""

from ultralytics import YOLO

class YoloV8PersonDetector:
    def __init__(self, model_path="yolov8n.pt", conf_th=0.25, iou_th=0.5, imgsz=1280):
        self.model = YOLO(model_path)
        self.conf_th = float(conf_th)
        self.iou_th = float(iou_th)
        self.imgsz = int(imgsz)
        self.PERSON_CLASS = 0  # COCO: person

    def detect(self, frame_bgr, conf_th=None, imgsz=None):
        # allow per-call overrides
        conf = self.conf_th if conf_th is None else float(conf_th)
        sz = self.imgsz if imgsz is None else int(imgsz)

        res = self.model.predict(
            frame_bgr,
            conf=conf,
            iou=self.iou_th,
            imgsz=sz,
            verbose=False
        )[0]

        dets = []
        if res.boxes is None:
            return dets

        for b in res.boxes:
            cls = int(b.cls.item())
            if cls != self.PERSON_CLASS:
                continue
            confb = float(b.conf.item())
            xyxy = b.xyxy[0].cpu().numpy().astype(np.float32)
            dets.append(Detection(xyxy=xyxy, conf=confb, cls=cls))
        return dets

"""**ByteTrack tracking + target selection**"""

import supervision as sv
import numpy as np

class ByteTrackWrapper:
    def __init__(
        self,
        track_activation_threshold: float = 0.22,
        lost_track_buffer: int = 50,
        minimum_matching_threshold: float = 0.7,
        frame_rate: int = 30,
        minimum_consecutive_frames: int = 1,
    ):
        self.tracker = sv.ByteTrack(
            track_activation_threshold=track_activation_threshold,
            lost_track_buffer=lost_track_buffer,
            minimum_matching_threshold=minimum_matching_threshold,
            frame_rate=frame_rate,
            minimum_consecutive_frames=minimum_consecutive_frames,
        )


    def update(self, frame_bgr: np.ndarray, dets: list[Detection]) -> list[Detection]:
        # Build supervision Detections
        if len(dets) == 0:
            sv_dets = sv.Detections.empty()
        else:
            xyxy = np.stack([d.xyxy for d in dets], axis=0)
            conf = np.array([d.conf for d in dets], dtype=np.float32)
            cls  = np.array([d.cls  for d in dets], dtype=np.int32)
            sv_dets = sv.Detections(xyxy=xyxy, confidence=conf, class_id=cls)

        # Call tracker with the right signature (varies across supervision versions)
        try:
            tracked = self.tracker.update_with_detections(sv_dets, frame_bgr)  # positional frame
        except TypeError:
            tracked = self.tracker.update_with_detections(sv_dets)             # no frame

        # Convert back to our Detection list
        out = []
        if len(tracked) == 0:
            return out

        for i in range(len(tracked)):
            out.append(
                Detection(
                    xyxy=tracked.xyxy[i].astype(np.float32),
                    conf=float(tracked.confidence[i]) if tracked.confidence is not None else 1.0,
                    cls=int(tracked.class_id[i]) if tracked.class_id is not None else 0,
                    track_id=int(tracked.tracker_id[i]) if tracked.tracker_id is not None else None,
                )
            )
        return out

def pick_main_track(tracked: list[Detection]) -> Detection | None:
    if not tracked:
        return None

    def area(d: Detection):
        x1, y1, x2, y2 = d.xyxy
        return max(0.0, (x2 - x1)) * max(0.0, (y2 - y1))

    return max(tracked, key=area)

def pick_main_track_scored(tracked, kf_pred_xy, last_box_area, max_dist_px):
    if len(tracked) == 0:
        return None

    kx, ky = float(kf_pred_xy[0]), float(kf_pred_xy[1])

    best = None
    best_score = 1e18

    for d in tracked:
        x1, y1, x2, y2 = d.xyxy
        cx = 0.5 * (x1 + x2)
        cy = 0.5 * (y1 + y2)

        dist = ((cx - kx) ** 2 + (cy - ky) ** 2) ** 0.5
        if dist > max_dist_px:
            continue

        area = max(1.0, (x2 - x1) * (y2 - y1))

        if last_box_area is None:
            scale_pen = 0.0
        else:
            ratio = area / max(1.0, last_box_area)
            scale_pen = (np.log(ratio) ** 2)

        score = dist ** 2 + 2000.0 * scale_pen

        if score < best_score:
            best_score = score
            best = d

    return best

def pick_track_with_lock(tracked: list[Detection], locked_id: int | None) -> Detection | None:
    if not tracked:
        return None

    if locked_id is not None:
        for d in tracked:
            if d.track_id == locked_id:
                return d
        return None  # locked id not visible this frame

    # if not locked yet -> choose best candidate with heuristics below
    return pick_main_track_heuristic(tracked)

"""**MediaPipe Tasks PoseLandmarker over ROI**"""

import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

class MediaPipePoseROI:
    def __init__(self, model_path: str, num_poses: int = 1):
        base_options = python.BaseOptions(model_asset_path=model_path)

        options = vision.PoseLandmarkerOptions(
            base_options=base_options,
            running_mode=vision.RunningMode.VIDEO,
            num_poses=num_poses,
            output_segmentation_masks=False,
        )
        self.landmarker = vision.PoseLandmarker.create_from_options(options)

    def estimate_com(self, roi_bgr: np.ndarray, crop_xyxy: np.ndarray, timestamp_ms: int) -> tuple[np.ndarray | None, float]:
        if roi_bgr is None or roi_bgr.size == 0:
            return None, 0.0

        roi_rgb = cv2.cvtColor(roi_bgr, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=roi_rgb)

        result = self.landmarker.detect_for_video(mp_image, timestamp_ms)
        if result.pose_landmarks is None or len(result.pose_landmarks) == 0:
            return None, 0.0

        lms = result.pose_landmarks[0]
        idxs = [11, 12, 23, 24]  # shoulders + hips

        pts = np.array([[lms[i].x, lms[i].y] for i in idxs], dtype=np.float32)

        vis_list = []
        for i in idxs:
            v = getattr(lms[i], "visibility", None)
            if v is not None:
                vis_list.append(float(v))
        score = float(np.mean(vis_list)) if len(vis_list) else 1.0

        if score < 0.4:
            return None, score

        roi_h, roi_w = roi_rgb.shape[:2]
        com_roi = np.array([pts[:, 0].mean() * roi_w, pts[:, 1].mean() * roi_h], dtype=np.float32)

        x1, y1, x2, y2 = crop_xyxy
        com_img = np.array([com_roi[0] + x1, com_roi[1] + y1], dtype=np.float32)
        return com_img, score

"""**Kalman filter (position + speed)**"""

from filterpy.kalman import KalmanFilter

class Kalman2D:
    def __init__(self, dt=1/30, process_var=50.0, meas_var=25.0):
        self.kf = KalmanFilter(dim_x=4, dim_z=2)

        self.kf.F = np.array([
            [1, 0, dt, 0],
            [0, 1, 0, dt],
            [0, 0, 1,  0],
            [0, 0, 0,  1],
        ], dtype=np.float32)

        self.kf.H = np.array([
            [1, 0, 0, 0],
            [0, 1, 0, 0],
        ], dtype=np.float32)

        self.kf.P *= 500.0
        self.kf.R = np.eye(2, dtype=np.float32) * meas_var

        q = process_var
        self.kf.Q = np.array([
            [q, 0, 0, 0],
            [0, q, 0, 0],
            [0, 0, q, 0],
            [0, 0, 0, q],
        ], dtype=np.float32)

        self.initialized = False

    def init(self, z: np.ndarray):
        self.kf.x = np.array([z[0], z[1], 0.0, 0.0], dtype=np.float32)
        self.initialized = True

    def predict_only(self) -> np.ndarray:
    # ONE prediction per frame
      self.kf.predict()
      return self.kf.x[:2].reshape(-1).copy()

    def update(self, z: np.ndarray | None) -> np.ndarray:
        # NO predict here (predict already done via predict_only)
        if z is not None:
            if not self.initialized:
                self.init(z)
            self.kf.update(z)
        return self.kf.x[:2].copy()

"""**Overlay detenction**"""

def filter_overlay_detections(dets, W, H):
    """
    Remove detections that overlap TV overlay regions.
    Safe version: reject only if (IoA high) AND (box is large).
    """
    # Bottom-left overlay (portrait + lower third)
    ox0, oy0, ox1, oy1 = int(0.00 * W), int(0.60 * H), int(0.55 * W), int(1.00 * H)

    # Optional: top-left scoreboard
    tx0, ty0, tx1, ty1 = int(0.00 * W), int(0.00 * H), int(0.45 * W), int(0.18 * H)

    bottom_region = (ox0, oy0, ox1, oy1)
    top_region = (tx0, ty0, tx1, ty1)

    FRAME_AREA = float(W * H)

    def ioa_and_area(box, region):
        x1, y1, x2, y2 = box
        rx1, ry1, rx2, ry2 = region

        ix1 = max(x1, rx1)
        iy1 = max(y1, ry1)
        ix2 = min(x2, rx2)
        iy2 = min(y2, ry2)

        iw = max(0, ix2 - ix1)
        ih = max(0, iy2 - iy1)
        inter = iw * ih

        area = max(1.0, (x2 - x1) * (y2 - y1))
        return inter / area, area

    out = []
    for d in dets:
        x1, y1, x2, y2 = map(int, d.xyxy)
        box = (x1, y1, x2, y2)

        ioa_b, area = ioa_and_area(box, bottom_region)
        ioa_t, _ = ioa_and_area(box, top_region)

        # overlay detections are typically much larger than the athlete box
        is_big = (area / FRAME_AREA) > 0.06   # tune 0.04–0.10

        if is_big and ioa_b > 0.25:
            continue
        if is_big and ioa_t > 0.35:
            continue

        out.append(d)

    return out

def crop_around_point(frame, cx, cy, size=800):
    H, W = frame.shape[:2]
    half = size // 2
    x1 = max(0, int(cx - half))
    y1 = max(0, int(cy - half))
    x2 = min(W, int(cx + half))
    y2 = min(H, int(cy + half))
    roi = frame[y1:y2, x1:x2].copy()
    return roi, (x1, y1, x2, y2)

def offset_dets(dets, offset_xyxy):
    ox1, oy1, _, _ = offset_xyxy
    for d in dets:
        x1, y1, x2, y2 = d.xyxy
        d.xyxy = (x1 + ox1, y1 + oy1, x2 + ox1, y2 + oy1)
    return dets

"""**Run end-to-end (video + CSV)**

**Run model**
"""

import os
import csv
import numpy as np
import cv2


def run_pipeline(
    video_path: str,
    out_video_path: str = "out_debug.mp4",
    out_csv_path: str = "trajectory_2d.csv",
    yolo_model: str = "yolov8m.pt",
    conf_th: float = 0.25,
    use_pose: bool = True,
    pose_model_path: str = "pose_landmarker_lite.task",
):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    dt = 1.0 / fps if (fps and fps > 1) else 1 / 30

    W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out = cv2.VideoWriter(
        out_video_path,
        fourcc,
        float(fps if fps and fps > 1 else 30),
        (W, H),
    )

    detector = YoloV8PersonDetector(
        model_path=yolo_model,
        conf_th=conf_th,
    )

    detector_fallback = YoloV8PersonDetector(
        model_path=yolo_model,
        conf_th=0.15,  # più permissivo
    )

    tracker = ByteTrackWrapper(
        track_activation_threshold=0.22,
        lost_track_buffer=50,
        minimum_matching_threshold=0.6,
        frame_rate=int(fps if fps and fps > 1 else 30),
        minimum_consecutive_frames=1,
    )

    pose = None
    if use_pose:
        if not os.path.exists(pose_model_path):
            raise RuntimeError(
                f"Pose model not found: {pose_model_path}. Run CELL 1 first."
            )
        pose = MediaPipePoseROI(model_path=pose_model_path)

    kf = Kalman2D(dt=dt)

    with open(out_csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(
            ["frame", "track_id", "meas_x", "meas_y", "kf_x", "kf_y", "pose_score", "used_pose"]
        )

        frame_idx = 0

        # ---- tracking state ----
        locked_id = None
        lost_count = 0
        MAX_LOST = 20          # ~0.7s @30fps
        REACQ_DIST = 180.0     # px, tune 140-220 for 1080p
        last_box_area = None

        while True:
            ok, frame = cap.read()
            if not ok:
                break

            # ---------------------------------------------------------
            # 0) KF PREDICT (ONCE PER FRAME)
            # ---------------------------------------------------------
            kf_pred = np.asarray(kf.predict_only()).reshape(-1)
            kx_pred, ky_pred = float(kf_pred[0]), float(kf_pred[1])

            # ---------------------------------------------------------
            # 1) DETECTION: FULL-FRAME OR ROI WHEN LOST
            # ---------------------------------------------------------
            use_roi = (lost_count > 0 and locked_id is not None and last_box_area is not None)

            dets = []

            if not use_roi:
                dets = detector.detect(frame)
                dets = filter_overlay_detections(dets, W, H)

                if len(dets) == 0:
                    dets = detector_fallback.detect(frame)
                    dets = filter_overlay_detections(dets, W, H)

            else:
                # ROI size adattiva
                if last_box_area is None:
                    ROI_SIZE = 900
                else:
                    ROI_SIZE = int(np.clip(3.0 * np.sqrt(last_box_area), 700, 1600))

                roi, roi_xyxy = crop_around_point(
                    frame,
                    kx_pred,
                    ky_pred,
                    size=ROI_SIZE,
                )

                if roi.size > 0:
                    dets_roi = detector_fallback.detect(roi)
                    dets_roi = offset_dets(dets_roi, roi_xyxy)
                    dets = filter_overlay_detections(dets_roi, W, H)

                # fallback full-frame se ROI fallisce
                if len(dets) == 0:
                    dets = detector_fallback.detect(frame)
                    dets = filter_overlay_detections(dets, W, H)

            # ---------------------------------------------------------
            # 2) TRACKER UPDATE (ONCE PER FRAME)
            # ---------------------------------------------------------
            tracked = tracker.update(frame, dets)

            # ---------------------------------------------------------
            # 3) SELECT MAIN TRACK (LOCK -> GATED KF -> FALLBACK)
            # ---------------------------------------------------------
            main = None

            # (A) prova a mantenere il locked_id
            if locked_id is not None:
                for d in tracked:
                    if d.track_id == locked_id:
                        main = d
                        break
            # (B) reacquire: score distanza KF + coerenza area (anti-overlay)
            if main is None and len(tracked) > 0:
                gate = REACQ_DIST * (1.0 + 0.08 * min(lost_count, 30))
                main = pick_main_track_scored(
                  tracked,
                  kf_pred_xy=kf_pred,
                  last_box_area=last_box_area,
                  max_dist_px=gate,
                )

                if main is not None and main.track_id is not None:
                    locked_id = main.track_id

            # (C) fallback: se ancora nulla ma c’è almeno una track, prendine una comunque
            #     (serve per "reboot" quando KF/lock sono andati)
            if main is None and len(tracked) > 0:
                main = pick_main_track(tracked)

            # (D) se ho preso una main valida, lock subito
            if main is not None and main.track_id is not None:
                locked_id = main.track_id

            # ---------------------------------------------------------
            # 4) UPDATE LOST COUNTERS + LAST BOX AREA
            # ---------------------------------------------------------
            if main is None:
                lost_count += 1
                if lost_count > MAX_LOST:
                    locked_id = None
            else:
                lost_count = 0
                x1, y1, x2, y2 = main.xyxy
                last_box_area = max(1.0, (x2 - x1) * (y2 - y1))

            # Optional debug overlay
            cv2.putText(
                frame,
                f"locked={locked_id} tracked={len(tracked)} lost={lost_count}",
                (10, 30),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                (255, 255, 255),
                2,
            )

            # ---------------------------------------------------------
            # MEASUREMENT (POSE IF AVAILABLE ELSE BBOX CENTER)
            # ---------------------------------------------------------
            meas = None
            pose_score = 0.0
            used_pose = 0

            if main is not None:
                roi_pose, crop_xyxy = adaptive_crop(frame, main.xyxy, scale=1.8)

                if use_pose and pose is not None:
                    timestamp_ms = int(frame_idx * dt * 1000)
                    pose_com, pose_score = pose.estimate_com(
                        roi_pose,
                        crop_xyxy,
                        timestamp_ms=timestamp_ms,
                    )
                else:
                    pose_com, pose_score = None, 0.0

                if pose_com is not None:
                    meas = np.asarray(pose_com).reshape(-1)
                    used_pose = 1
                else:
                    meas = np.asarray(measurement_from(main, None)).reshape(-1)
                    used_pose = 0

                # Draw bbox
                x1, y1, x2, y2 = clamp_box(main.xyxy, W, H)
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.putText(
                    frame,
                    f"id={main.track_id} conf={main.conf:.2f}",
                    (x1, max(0, y1 - 10)),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6,
                    (0, 255, 0),
                    2,
                )

                # Draw measurement
                mx, my = int(meas[0]), int(meas[1])
                cv2.circle(frame, (mx, my), 4, (0, 255, 255), -1)

                if used_pose:
                    cv2.putText(
                        frame,
                        f"pose={pose_score:.2f}",
                        (mx + 6, my - 6),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.6,
                        (0, 255, 255),
                        2,
                    )

            # ---------------------------------------------------------
            # KALMAN UPDATE + DRAW
            # ---------------------------------------------------------
            kf_pos = np.asarray(kf.update(meas)).reshape(-1)
            kx, ky = int(kf_pos[0]), int(kf_pos[1])

            cv2.circle(frame, (kx, ky), 4, (255, 0, 0), -1)
            cv2.putText(
                frame,
                "KF",
                (kx + 6, ky - 6),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                (255, 0, 0),
                2,
            )

            # ---------------------------------------------------------
            # CSV LOG
            # ---------------------------------------------------------
            if main is not None and meas is not None:
                writer.writerow(
                    [
                        frame_idx,
                        main.track_id,
                        float(meas[0]),
                        float(meas[1]),
                        float(kf_pos[0]),
                        float(kf_pos[1]),
                        float(pose_score),
                        used_pose,
                    ]
                )
            else:
                writer.writerow(
                    [
                        frame_idx,
                        None,
                        None,
                        None,
                        float(kf_pos[0]),
                        float(kf_pos[1]),
                        float(pose_score),
                        used_pose,
                    ]
                )

            out.write(frame)
            frame_idx += 1

    cap.release()
    out.release()

    print("Saved video:", out_video_path)
    print("Saved csv:", out_csv_path)

run_pipeline(
    video_path="20.mp4",
    out_video_path="20out.mp4",
    out_csv_path="21trajectory_2d.csv",
    conf_th=0.25,
    use_pose=False
)

"""**Run with pose (more precise)**"""

run_pipeline(
    video_path="21.mp4",
    out_video_path="201a.mp4",
    out_csv_path="trajectory_2d_pose.csv",
    conf_th=0.25,
    use_pose=True,
    pose_model_path="pose_landmarker_lite.task",
)