# -*- coding: utf-8 -*-
"""IACVfineV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lsVk8rhatHzN0wuZQmOWH2sbuyGg6pAw

Connect to the project drive
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

# %cd /content/drive/MyDrive/SkiJumping/

"""**Install mediapipe**"""
!pip -q install ultralytics opencv-python filterpy supervision mediapipe

"""**Download MediaPipe PoseLandmarker model**"""

import os
import urllib.request

MODEL_URL = "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task"
MODEL_PATH = "pose_landmarker_lite.task"

if not os.path.exists(MODEL_PATH):
    print("Downloading MediaPipe PoseLandmarker model...")
    urllib.request.urlretrieve(MODEL_URL, MODEL_PATH)
    print("Saved:", MODEL_PATH)
else:
    print("Model already present:", MODEL_PATH)

"""Segment Anything Model (SAM)"""
!pip install git+https://github.com/facebookresearch/segment-anything.git


from segment_anything import sam_model_registry, SamPredictor
import torch

class SAMSegmenter:
  def __init__(self, model_type="vit_b", checkpoint="models/sam_vit_b_01ec64.pth"):
    self.device = "cuda" if torch.cuda.is_available() else "cpu"
    sam = sam_model_registry[model_type](checkpoint=checkpoint)
    sam.to(device=self.device)
    self.predictor = SamPredictor(sam)

  def get_com(self, frame, bbox):
    self.predictor.set_image(frame)
    input_box = np.array(bbox)

    masks, scores, _ = self.predictor.predict(
        box=input_box[None, :],
        multimask_output=False
    )
    mask = masks[0]

    M = cv2.moments(mask.astype(np.uint8))
    if M["m00"] != 0:
      cX = int(M["m10"] / M["m00"])
      cY = int(M["m01"] / M["m00"])
      return (cX, cY), mask
    return None, None

"""**data structures + helper**"""

import cv2
import numpy as np
from dataclasses import dataclass

@dataclass
class Detection:
    xyxy: np.ndarray   # (4,) float32
    conf: float
    cls: int
    track_id: int | None = None

def clamp_box(xyxy, w, h):
    x1, y1, x2, y2 = xyxy
    x1 = max(0, min(int(x1), w - 1))
    y1 = max(0, min(int(y1), h - 1))
    x2 = max(0, min(int(x2), w - 1))
    y2 = max(0, min(int(y2), h - 1))
    if x2 <= x1: x2 = min(w - 1, x1 + 1)
    if y2 <= y1: y2 = min(h - 1, y1 + 1)
    return np.array([x1, y1, x2, y2], dtype=np.int32)

def xyxy_center(xyxy: np.ndarray) -> np.ndarray:
    x1, y1, x2, y2 = xyxy
    return np.array([(x1 + x2) / 2.0, (y1 + y2) / 2.0], dtype=np.float32)

def adaptive_crop(frame_bgr, xyxy, scale=2.2):
    h, w = frame_bgr.shape[:2]
    x1, y1, x2, y2 = xyxy
    cx, cy = (x1 + x2) / 2, (y1 + y2) / 2
    bw, bh = (x2 - x1), (y2 - y1)

    bw2, bh2 = bw * scale / 2, bh * scale / 2
    crop_xyxy = np.array([cx - bw2, cy - bh2, cx + bw2, cy + bh2], dtype=np.float32)
    crop_xyxy = clamp_box(crop_xyxy, w, h)

    x1, y1, x2, y2 = crop_xyxy
    roi = frame_bgr[y1:y2, x1:x2].copy()
    return roi, crop_xyxy

def measurement_from(det: Detection, pose_com: np.ndarray | None, prefer_pose=True) -> np.ndarray:
    if prefer_pose and pose_com is not None:
        return pose_com
    return xyxy_center(det.xyxy)

"""**YOLOv8 detector (person)**"""

from ultralytics import YOLO

class SkiJumperDetector:
    def __init__(self, model_path='models/best.pt', conf_th=0.5, iou_th=0.5, imgsz=640):
        self.model = YOLO(model_path)
        self.conf_th = float(conf_th)
        self.iou_th = float(iou_th)
        self.imgsz = int(imgsz)
        self.JUMPER_CLASS = 0  # COCO: person

    def detect_and_track(self, frame_bgr, conf_th=None, imgsz=None):
        # allow per-call overrides
        conf = self.conf_th if conf_th is None else float(conf_th)
        sz = self.imgsz if imgsz is None else int(imgsz)

        results = self.model.track(
          frame_bgr,
          conf=conf,
          iou=self.iou_th,
          imgsz=sz,
          persist = True,
          verbose=False,
          classes=[self.JUMPER_CLASS]
        )[0]

        dets = []
        if results.boxes is None or results.boxes.id is None:
          if results.boxes is None:
              return dets

        for b in results.boxes:
          cls = int(b.cls.item())
          confb = float(b.conf.item())
          xyxy = b.xyxy[0].cpu().numpy().astype(np.float32)

          tid = int(b.id.item()) if b.id is not None else None

          dets.append(Detection(
            xyxy=xyxy,
            conf=confb,
            cls=cls,
            track_id=tid
          ))
        return dets

"""**Target selection**

ByteTrackWrapper deleted - we use embedded tracker from YOLO
"""

def pick_main_track(tracked: list[Detection], last_main_id: int | None = None) -> Detection | None:
    if not tracked:
        return None

    # if jumper already tracked
    if last_main_id is not None:
      for d in tracked:
        if d.track_id == last_main_id:
          return d

    # if no ID (start or lost bounding box)
    def area(d: Detection):
        x1, y1, x2, y2 = d.xyxy
        return max(0.0, (x2 - x1)) * max(0.0, (y2 - y1))

    return max(tracked, key=area)

def pick_best_detection(tracked_dets, kf_pos):
  if not tracked_dets:
    return None

  if len(tracked_dets) == 1:
    return tracked_dets[0]

  def dist_to_kf(d):
    cx, cy = xyxy_center(d.xyxy)
    return np.sqrt((cx - kf_pos[0])**2 + (cy - kf_pos[1])**2)

  return min(tracked_dets, key=dist_to_kf)

"""**MediaPipe Tasks PoseLandmarker over ROI**"""

import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

class MediaPipePoseROI:
    def __init__(self, model_path: str, num_poses: int = 1):
        base_options = python.BaseOptions(model_asset_path=model_path)

        options = vision.PoseLandmarkerOptions(
            base_options=base_options,
            running_mode=vision.RunningMode.VIDEO,
            num_poses=num_poses,
            output_segmentation_masks=False,
        )
        self.landmarker = vision.PoseLandmarker.create_from_options(options)

    def estimate_com(self, roi_bgr: np.ndarray, crop_xyxy: np.ndarray, timestamp_ms: int) -> tuple[np.ndarray | None, float]:
        if roi_bgr is None or roi_bgr.size == 0:
            return None, 0.0

        roi_rgb = cv2.cvtColor(roi_bgr, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=roi_rgb)

        result = self.landmarker.detect_for_video(mp_image, timestamp_ms)
        if result.pose_landmarks is None or len(result.pose_landmarks) == 0:
            return None, 0.0

        lms = result.pose_landmarks[0]
        idxs = [11, 12, 23, 24]  # shoulders + hips

        pts = np.array([[lms[i].x, lms[i].y] for i in idxs], dtype=np.float32)

        vis_list = []
        for i in idxs:
            v = getattr(lms[i], "visibility", None)
            if v is not None:
                vis_list.append(float(v))
        score = float(np.mean(vis_list)) if len(vis_list) else 1.0

        if score < 0.4:
            return None, score

        roi_h, roi_w = roi_rgb.shape[:2]
        com_roi = np.array([pts[:, 0].mean() * roi_w, pts[:, 1].mean() * roi_h], dtype=np.float32)

        x1, y1, x2, y2 = crop_xyxy
        com_img = np.array([com_roi[0] + x1, com_roi[1] + y1], dtype=np.float32)
        return com_img, score

"""**Kalman filter (position + speed)**"""

from filterpy.kalman import KalmanFilter

class Kalman2D:
    def __init__(self, dt=1/30, process_var=200, meas_var=0.05):
        self.kf = KalmanFilter(dim_x=4, dim_z=2)

        self.kf.F = np.array([
            [1, 0, dt, 0],
            [0, 1, 0, dt],
            [0, 0, 1,  0],
            [0, 0, 0,  1],
        ], dtype=np.float32)

        self.kf.H = np.array([
            [1, 0, 0, 0],
            [0, 1, 0, 0],
        ], dtype=np.float32)

        self.kf.P *= 100.0
        self.kf.R = np.eye(2, dtype=np.float32) * meas_var

        q = process_var
        self.kf.Q = np.array([
            [0.25*dt**4, 0, 0.5*dt**3, 0],
            [0, 0.25*dt**4, 0, 0.5*dt**3],
            [0.5*dt**3, 0, dt**2, 0],
            [0, 0.5*dt**3, 0, dt**2],
        ], dtype=np.float32) * q

        self.initialized = False

    def init(self, z: np.ndarray):
        self.kf.x = np.array([z[0], z[1], 0.0, 0.0], dtype=np.float32)
        self.initialized = True

    def predict_only(self) -> np.ndarray:
    # ONE prediction per frame
      self.kf.predict()
      return self.kf.x[:2].reshape(-1).copy()

    def update(self, z: np.ndarray | None) -> np.ndarray:
        # NO predict here (predict already done via predict_only)
        if z is not None:
            if not self.initialized:
                self.init(z)
            self.kf.update(z)
        return self.kf.x[:2].copy()

"""**Run model**"""

import os
import csv
import numpy as np
import cv2


def run_pipeline(
    video_path: str,
    out_video_path: str = "/outputs/output_result.mp4",
    out_csv_path: str = "/outputs/trajectory_2d.csv",
    yolo_model: str = "/models/best.pt",
    conf_th: float = 0.5,
    use_pose: bool = False,
    pose_model_path: str = "pose_landmarker_lite.task",
    use_sam = False
):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    dt = 1.0 / fps if (fps and fps > 1) else 1 / 30

    W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out = cv2.VideoWriter(
        out_video_path,
        fourcc,
        float(fps if fps and fps > 1 else 30),
        (W, H),
    )

    detector = SkiJumperDetector(
        model_path=yolo_model,
        conf_th=conf_th,
        imgsz=640
    )

    pose = None
    if use_pose:
        if not os.path.exists(pose_model_path):
            raise RuntimeError(
                f"Pose model not found: {pose_model_path}. Run CELL 1 first."
            )
        pose = MediaPipePoseROI(model_path=pose_model_path)

    sam = None
    if use_sam:
      sam = SAMSegmenter()

    kf = Kalman2D(dt=dt)

    with open(out_csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(
            ["frame", "track_id","x1", "y1", "x2", "y2", "meas_x", "meas_y", "kf_x", "kf_y", "pose_score", "used_pose", "used_sam"]
        )

        frame_idx = 0

        # While for each frame
        while True:
            ok, frame = cap.read()
            if not ok:
                break

            # 0) KF PREDICT (ONCE PER FRAME)
            kf_pred = kf.predict_only()


            # 1) DETECTION: FULL-FRAME OR ROI WHEN LOST
            detections = detector.detect_and_track(frame)

            main_jumper = pick_best_detection(detections, kf_pred)

            meas = None
            pose_score = 0.0
            used_pose = 0

            if main_jumper is not None:
              current_meas = xyxy_center(main_jumper.xyxy)

              # detect camera change
              dist = np.sqrt((current_meas[0] - kf_pred[0])**2 + (current_meas[1] - kf_pred[1])**2)

              if dist > 300:
                  kf.init(current_meas)


              # MediaPipe Pose
              roi_pose, crop_xyxy = adaptive_crop(frame, main_jumper.xyxy, scale=2.0)

              if pose:
                timestamp_ms = int(frame_idx * dt * 1000)
                pose_com, pose_score = pose.estimate_com(roi_pose, crop_xyxy, timestamp_ms)
              else:
                pose_com = None

              if pose_com is not None:
                meas = pose_com
                used_pose = 1
                color_point = (0, 255, 255)
              else:
                meas = xyxy_center(main_jumper.xyxy)
                used_pose = 0
                color_point = (255, 255, 0)

              # SAM
              used_sam = 0
              if sam:
                sam_com, jumper_mask = sam.get_com(frame, main_jumper.xyxy)

                if sam_com is not None:
                  meas = sam_com
                  used_sam = 1
                  color_point = (0, 0, 255)
                else:
                  meas = xyxy_center(main_jumper.xyxy)
                  used_sam = 0
                  color_point = (255, 255, 0)

              # Drawing
              x1, y1, x2, y2 = map(int, main_jumper.xyxy)
              cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
              cv2.putText(frame, f"ID:{main_jumper.track_id}", (x1, max(0, y1-10)),
                          cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
              cv2.circle(frame, (int(meas[0]), int(meas[1])), 8, color_point, -1)

              # KALMAN UPDATE + DRAW
              kf_pos = kf.update(meas)
              cv2.circle(frame, (int(kf_pos[0]), int(kf_pos[1])), 8, (255, 0, 0), -1)

              # LOG + CSV LOG
              print(f"Frame: {frame_idx} - TrackID: {main_jumper.track_id} - Meas_x: {meas[0]} - Meas_y: {meas[1]} - Kf_x: {kf_pos[0]} - Kf_y: {kf_pos[1]}")
              row = [frame_idx, main_jumper.track_id, x1, y1, x2, y2,
                    float(meas[0]) if meas is not None else None,
                    float(meas[1]) if meas is not None else None,
                    kf_pos[0], kf_pos[1], pose_score, used_pose, used_sam]
              writer.writerow(row)

              out.write(frame)
            frame_idx += 1

    cap.release()
    out.release()

    print("Saved video:", out_video_path)
    print("Saved csv:", out_csv_path)

run_pipeline(
    video_path="/videos/O_20.mp4",
    out_video_path="/outputs/20out.mp4",
    out_csv_path="/outputs/20trajectory_2d.csv",
    conf_th=0.5,
    use_pose=False,
    use_sam=True
)